#!/bin/sh

# You can put local mirrors here if you want
mirror=http://deb.debian.org/debian/

# Detect target architecture and filter args
temp=""
arch=$(dpkg --print-architecture)
dist="unstable"
lb_opts=""
while [ $# -gt 0 ]; do
	arg="$1"
	case "$arg" in
	-a|--arch|--architecture|--architectures)
		arch="$2"
		temp="$temp "'"'"$arg"'"'
		temp="$temp "'"'"$2"'"'
		shift
		;;
	--sid|--unstable)
		dist="unstable"
		;;
	--testing)
		dist="testing"
		;;
	*)
		temp="$temp "'"'"$arg"'"'
		;;
	esac
	shift
done
eval set -- "$temp"

case "$arch" in
    amd64)
	lb_opts="$lb_opts --debian-installer live"
	lb_opts="$lb_opts --linux-flavours amd64"
    ;;
    i386)
	lb_opts="$lb_opts --debian-installer live"
	lb_opts="$lb_opts --linux-flavours 686-pae"
    ;;
    armel|armhf)
	lb_opts="$lb_opts --binary-images hdd --binary-filesystem ext4 --chroot-filesystem none"
    ;;
    *)
	echo "WARNING: configuration not tested on arch $arch" >&2
    ;;
esac

lb config noauto \
	--archive-areas "main contrib non-free-firmware non-free" \
	--bootappend-live "boot=live quiet splash" \
	--debian-installer-distribution daily \
	--distribution "$dist" \
	--firmware-binary true \
	--firmware-chroot true \
	--image-name "xebian-$dist" \
	--iso-application "Xebian" \
	--iso-publisher "Xebian team" \
	--linux-packages linux-image \
	--mirror-bootstrap "$mirror" \
	--win32-loader false \
	$lb_opts \
	"$@"
