#!/bin/sh

# You can put local mirrors here if you want
mirror=http://deb.debian.org/debian/

# Detect target architecture and filter args
temp=""
arch=$(dpkg --print-architecture)
dist="sid"
lb_opts=""
while [ $# -gt 0 ]; do
	arg="$1"
	case "$arg" in
	-a|--arch|--architecture|--architectures)
		arch="$2"
		temp="$temp "'"'"$arg"'"'
		temp="$temp "'"'"$2"'"'
		shift
		;;
	--liquorix)
		liquorix="1"
		;;
	--sid|--unstable)
		dist="sid"
		;;
	--testing)
		dist="testing"
		;;
	*)
		temp="$temp "'"'"$arg"'"'
		;;
	esac
	shift
done
eval set -- "$temp"

if [ -n "$liquorix" ]; then
	mkdir -p config/archives
	echo "deb http://mirror.unit193.net/liquorix sid main" \
		> config/archives/liquorix.list.chroot
	echo "deb http://mirror.unit193.net/liquorix sid main" \
		> config/archives/liquorix.list.binary
fi

case "$arch" in
    amd64)
	lb_opts="$lb_opts --debian-installer live"
	if [ -n "$liquorix" ]; then
	    lb_opts="$lb_opts --linux-flavours liquorix-amd64"
	else
	    lb_opts="$lb_opts --linux-flavours amd64"
	fi
    ;;
    i386)
	lb_opts="$lb_opts --debian-installer live"
	if [ -n "$liquorix" ]; then
	    lb_opts="$lb_opts --linux-flavours liquorix-686-pae"
	else
	    lb_opts="$lb_opts --linux-flavours 686-pae"
	fi
    ;;
    armel|armhf)
	lb_opts="$lb_opts --binary-images hdd --binary-filesystem ext4 --chroot-filesystem none"
    ;;
    *)
	echo "WARNING: configuration not tested on arch $arch" >&2
    ;;
esac

lb config noauto \
	--archive-areas "main contrib non-free" \
	--bootappend-live "boot=live" \
	--debian-installer-distribution daily \
	--distribution "$dist" \
	--firmware-binary true \
	--firmware-chroot true \
	--image-name "xebian-$dist" \
	--iso-application "Xebian" \
	--iso-publisher "Unit 193" \
	--iso-volume "Xebian Live" \
	--linux-packages linux-image \
	--mirror-bootstrap "$mirror" \
	--win32-loader false \
	$lb_opts \
	"$@"
